version: "3" 
services:
  # Application service layer
  sql:
    build:
      context: ./sql
    volumes:
      - "./sql/crow/src:/crow"
    ports:
      - "80:9000"
    links:
      - bd2
    restart: on-failure
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=123.456
 
  # Data persistence service layer
  bd2:
    image: mysql:5.6
    volumes:
      - "db_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456
      - MYSQL_DATABASE=teste

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - bd2
    ports:
      - 801:80
    environment:
      - PMA_HOST=bd2

  theia:
    image: theiaide/theia
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/project

volumes:
  db_data:

