version: "3" 
services:
  # Application service layer
  c:
    build:
      context: ./c
    volumes:
      - "./c/HelloWorldDocker:/HelloWorldDocker"
    ports:
      - "80:9000"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=123.456
 
  # Data persistence service layer
  mysql:
    image: mysql:5.7.20
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 801:80
    environment:
      - PMA_HOST=mysql

  theia:
    image: theiaide/theia
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/project

volumes:
  db_data:

